.TH AMTOG "1" "May 2009" "nauty 2.4" "User Commands"
.SH NAME
amtog \- Read graphs in matrix format.
.SH SYNOPSIS
.B amtog
[\fI\-n#sghq\fR] [\fIinfile \fR[\fIoutfile\fR]]
.SH DESCRIPTION
.IP
Read graphs in matrix format.
.TP
\fB\-n\fR#
Set the initial graph order to # (no default).
This can be overridden in the input.
.TP
\fB\-g\fR
Write the output in graph6 format (default).
.TP
\fB\-s\fR
Write the output in sparse6 format.
.TP
\fB\-h\fR
Write a header (according to \fB\-g\fR or \fB\-s\fR).
.TP
\fB\-q\fR
Suppress auxiliary information.
.IP
Input consists of a sequence of commands restricted to:
.TP
n=#
set number of vertices (no default)
The = is optional.
.TP
m
Matrix to follow (01 any spacing or no spacing)
An 'm' is also assumed if 0 or 1 is encountered.
.TP
M
Complement of matrix to follow (as m)
.TP
t
Upper triangle of matrix to follow, row by row
.IP
excluding the diagonal. (01 in any or no spacing)
.TP
T
Complement of upper triangle to follow (as t)
.TP
q
exit (optional)
