.TH CATG "1" "May 2009" "nauty 2.4" "User Commands"
.SH NAME
catg \- Copy files to stdout with all but the first header removed.
.SH SYNOPSIS
.B catg
[\fI-xv\fR] [\fIinfile\fR]...
.SH DESCRIPTION
.IP
Copy files to stdout with all but the first header removed.
.TP
\fB\-x\fR
Don't write a header.
In the absence of \fB\-x\fR, a header is written if
there is one in the first input file.
.TP
\fB\-v\fR
Summarize to stderr.
