.TH COMPLG "1" "May 2009" "nauty 2.4" "User Commands"
.SH NAME
complg \- Take the complements of a file of graphs.
.SH SYNOPSIS
.B complg
[\fI-lrq\fR] [\fIinfile \fR[\fIoutfile\fR]]
.SH DESCRIPTION
.IP
Take the complements of a file of graphs.
.IP
The output file has a header if and only if the input file does.
.TP
\fB\-r\fR
Only complement if the complement has fewer edges.
.TP
\fB\-l\fR
Canonically label outputs.
.TP
\fB\-q\fR
Suppress auxiliary information.
