.TH COPYG "1" "May 2009" "nauty 2.4" "User Commands"
.SH NAME
copyg \- Copy a file of graphs with possible format conversion.
.SH SYNOPSIS
.B copyg
[\fI\-gsfp#:#qhx\fR] [\fIinfile \fR[\fIoutfile\fR]]
.SH DESCRIPTION
.IP
Copy a file of graphs with possible format conversion.
.TP
\fB\-g\fR
Use graph6 format for output
.TP
\fB\-s\fR
Use sparse6 format for output
In the absence of \fB\-g\fR and \fB\-s\fR, the format depends on
the header or, if none, the first input line.
.HP
\fB\-p\fR# \fB\-p\fR#:#
.IP
Specify range of input lines (first is 1)
.TP
\fB\-f\fR
With \fB\-p\fR, assume input lines of fixed length
.IP
(ignored if header or first line has sparse6 format).
.TP
\fB\-h\fR
Write a header.
.TP
\fB\-x\fR
Don't write a header.
In the absence of \fB\-h\fR and \fB\-x\fR, a header is written if
there is one in the input.
.TP
\fB\-q\fR
Suppress auxiliary output.
