.TH DRETOG "1" "May 2009" "nauty 2.4" "User Commands"
.SH NAME
dretog \- Read graphs in dreadnaut format.
.SH SYNOPSIS
.B dretog
[\fI\-n#o#sghq\fR] [\fIinfile \fR[\fIoutfile\fR]]
.SH DESCRIPTION
.IP
Read graphs in dreadnaut format.
.TP
\fB\-o\fR#
Label vertices starting at # (default 0).
This can be overridden in the input.
.TP
\fB\-n\fR#
Set the initial graph order to # (no default).
This can be overridden in the input.
.TP
\fB\-g\fR
Use graph6 format (default).
.TP
\fB\-s\fR
Use sparse6 format.
.TP
\fB\-h\fR
Write a header (according to \fB\-g\fR or \fB\-s\fR).
.IP
Input consists of a sequence of dreadnaut commands restricted to:
.TP
n=#
set number of vertices (no default)
The = is optional.
.TP
$=#
set label of first vertex (default 0)
The = is optional.
.TP
$$
return origin to initial value (see \fB\-o\fR#)
.TP
".." and !..\en
comments to ignore
.TP
g
specify graph to follow (as dreadnaut format)
Can be omitted if first character of graph is a digit or ';'.
.TP
q
exit (optional)
