.TH GENBG "1" "May 2009" "nauty 2.4" "User Commands"
.SH NAME
genbg \- [mine[:maxe]] [res/mod] [file]
.SH SYNOPSIS
.B genbg
[\fI\-c \-ugsn \-vq \-lzF\fR] [\fI\-Z#\fR] [\fI\-d#|\-d#:#\fR] [\fI\-D#|\-D#:#\fR] \fIn1 n2\fR
.SH DESCRIPTION
.IP
[mine[:maxe]] [res/mod] [file]
.IP
Find all bicoloured graphs of a specified class.
.TP
n1
: the number of vertices in the first class
.TP
n2
: the number of vertices in the second class
.IP
mine:maxe : a range for the number of edges
.IP
#:0 means '# or more' except in the case 0:0
.IP
res/mod : only generate subset res out of subsets 0..mod\-1
.IP
file : the name of the output file (defailt stdout)
.TP
\fB\-c\fR
: only write connected graphs
.TP
\fB\-z\fR
: all the vertices in the second class must have
.IP
different neighbourhoods
.TP
\fB\-F\fR
: the vertices in the second class must have at least two
.IP
neighbours of degree at least 2
.TP
\fB\-L\fR
: there is no vertex in the first class whose removal leaves
.IP
the vertices in the second class unreachable from each other
.TP
\fB\-Z\fR#
: two vertices in the second class may have at most # common nbrs
.TP
\fB\-D\fR#
: specify an upper bound for the maximum degree.
.TP
Example: \fB\-D6\fR.
You can also give separate maxima for the
.IP
two parts, for example: \fB\-D5\fR:6
.TP
\fB\-d\fR#
: specify a lower bound for the minimum degree.
.IP
Again, you can specify it separately for the two parts: \fB\-d1\fR:2
.TP
\fB\-n\fR
: use nauty format for output
.TP
\fB\-g\fR
: use graph6 format for output (default)
.TP
\fB\-s\fR
: use sparse6 format for output
.TP
\fB\-a\fR
: use Greechie diagram format for output
.TP
\fB\-u\fR
: do not output any graphs, just generate and count them
.TP
\fB\-v\fR
: display counts by number of edges to stderr
.TP
\fB\-l\fR
: canonically label output graphs (using the 2\-part colouring)
.TP
\fB\-q\fR
: suppress auxiliary output
.IP
See program text for much more information.
