.TH GENRANG "1" "May 2009" "nauty 2.4" "User Commands"
.SH NAME
genrang \- Generate random graphs.
.SH SYNOPSIS
.B genrang
[\fI-P#|-P#/#|-e#|-r#|-R#\fR] [\fI-a\fR] [\fI-s|-g\fR] [\fI-S#\fR] [\fI-q\fR] \fIn num \fR[\fIoutfile\fR]
.SH DESCRIPTION
.IP
Generate random graphs.
.TP
n
: number of vertices
.IP
num : number of graphs
.TP
\fB\-s\fR
: Write in sparse6 format (default)
.TP
\fB\-g\fR
: Write in graph6 format
.HP
\fB\-P\fR#/# : Give edge probability; \fB\-P\fR# means \fB\-P1\fR/#.
.HP
\fB\-e\fR# : Give the number of edges
.HP
\fB\-r\fR# : Make regular of specified (0\-8) degree
.HP
\fB\-R\fR# : Make regular of specified (0\-8) degree but output
.IP
as vertex count, edgecount, then list of edges
.TP
\fB\-a\fR
: Make invariant under a random permutation
.HP
\fB\-S\fR# : Specify random generator seed (default nondeterministic)
.TP
\fB\-q\fR
: suppress auxiliary output
.IP
Incompatible: \fB\-P\fR,\-e,\-r,\-R; \fB\-s\fR,\-g,\-R; \fB\-R\fR,\-a.
