.TH LABELG "1" "May 2009" "nauty 2.4" "User Commands"
.SH NAME
labelg \- Canonically label a file of graphs.
.SH SYNOPSIS
.B labelg
[\fI-qsg\fR] [\fI-fxxx\fR] [\fI-S\fR] [\fI-i# -I#:# -K#\fR] [\fIinfile \fR[\fIoutfile\fR]]
.SH DESCRIPTION
.IP
Canonically label a file of graphs.
.TP
\fB\-s\fR
force output to sparse6 format
.TP
\fB\-g\fR
force output to graph6 format
If neither \fB\-s\fR or \fB\-g\fR are given, the output format is
determined by the header or, if there is none, by the
format of the first input graph. Also see \fB\-S\fR.
.TP
\fB\-S\fR
Use sparse representation internally.
.IP
Note that this changes the canonical labelling.
Only sparse6 output is supported in this case.
Multiple edges are not supported.  One loop per vertex is ok.
.IP
The output file will have a header if and only if the input file does.
.TP
\fB\-fxxx\fR
Specify a partition of the point set.  xxx is any
.TP
string of ASCII characters except nul.
This string is
.IP
considered extended to infinity on the right with the
character 'z'.  One character is associated with each point,
in the order given.  The labelling used obeys these rules:
.IP
(1) the new order of the points is such that the associated
.IP
characters are in ASCII ascending order
.IP
(2) if two graphs are labelled using the same string xxx,
.IP
the output graphs are identical iff there is an
associated\-character\-preserving isomorphism between them.
No option can be concatenated to the right of \fB\-f\fR.
.TP
\fB\-i\fR#
select an invariant (1 = twopaths, 2 = adjtriang(K), 3 = triples,
.IP
4 = quadruples, 5 = celltrips, 6 = cellquads, 7 = cellquins,
8 = distances(K), 9 = indsets(K), 10 = cliques(K), 11 = cellcliq(K),
.IP
12 = cellind(K), 13 = adjacencies, 14 = cellfano, 15 = cellfano2)
.TP
\fB\-I\fR#:#
select mininvarlevel and maxinvarlevel (default 1:1)
.TP
\fB\-K\fR#
select invararg (default 3)
.TP
\fB\-q\fR
suppress auxiliary information
