.TH MULTIG "1" "May 2009" "nauty 2.4" "User Commands"
.SH NAME
multig \- Read undirected loop\-free graphs and replace their edges with multiple
.SH SYNOPSIS
.B multig
[\fI-q\fR] [\fI-u|-T|-G|-A|-B\fR] [\fI-e#|-e#:#\fR] [\fI-m#\fR] [\fI-f#\fR] [\fI-D#|-r#|-l#\fR] [\fIinfile \fR[\fIoutfile\fR]]
.SH DESCRIPTION
.IP
Read undirected loop\-free graphs and replace their edges with multiple
.IP
edges in all possible ways (multiplicity at least 1).
Isomorphic multigraphs derived from the same input are suppressed.
If the input graphs are non\-isomorphic then the output graphs are also.
.TP
\fB\-e\fR# | \fB\-e\fR#:#
specify a value or range of the total number of edges
counting multiplicities
.HP
\fB\-m\fR# maximum edge multiplicity (minimum is 1)
.HP
\fB\-D\fR# upper bound on maximum degree
.HP
\fB\-r\fR# make regular of specified degree (incompatible with \fB\-l\fR, \fB\-D\fR, \fB\-e\fR)
.HP
\fB\-l\fR# make regular multigraphs with multiloops, degree #
.IP
(incompatible with \fB\-r\fR, \fB\-D\fR, \fB\-e\fR)
.IP
Either \fB\-l\fR, \fB\-r\fR, \fB\-D\fR, \fB\-e\fR or \fB\-m\fR with a finite maximum must be given
\fB\-f\fR# Use the group that fixes the first # vertices setwise
\fB\-T\fR  use a simple text output format (nv ne {v1 v2 mult})
\fB\-G\fR  like \fB\-T\fR but includes group size as third item (if less than 10^10)
.IP
The group size does not include exchange of isolated vertices.
.TP
\fB\-A\fR
write as the upper triangle of an adjacency matrix, row by row,
including the diagonal, and preceded by the number of vertices
.TP
\fB\-B\fR
write as an integer matrix preceded by the number of rows and
number of columns, where \fB\-f\fR determines the number of rows
.TP
\fB\-u\fR
no output, just count them
.TP
\fB\-q\fR
suppress auxiliary information
