Document: nauty
Title: Debian nauty Manual
Author: <insert document author here>
Abstract: This manual describes what nauty is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nauty/nauty.sgml.gz

Format: postscript
Files: /usr/share/doc/nauty/nauty.ps.gz

Format: text
Files: /usr/share/doc/nauty/nauty.text.gz

Format: HTML
Index: /usr/share/doc/nauty/html/index.html
Files: /usr/share/doc/nauty/html/*.html

  
