.TH PLANARG "1" "May 2009" "nauty 2.4" "User Commands"
.SH NAME
planarg \- For each input, write to output if planar.
.SH SYNOPSIS
.B planarg
[\fI-v\fR] [\fI-nVq\fR] [\fI-p|-u\fR] [\fIinfile \fR[\fIoutfile\fR]]
.SH DESCRIPTION
.IP
For each input, write to output if planar.
.IP
The output file has a header if and only if the input file does.
.TP
\fB\-v\fR
Write non\-planar graphs instead of planar graphs
.TP
\fB\-V\fR
Write report on every input
.TP
\fB\-u\fR
Don't write anything, just count
.TP
\fB\-p\fR
Write in planar_code if planar (without \fB\-p\fR, same format as input)
.TP
\fB\-k\fR
Follow each non\-planar output with an obstruction in sparse6
format (implies \fB\-v\fR, incompatible with \fB\-p\fR)
.TP
\fB\-n\fR
Suppress checking of the result
.TP
\fB\-q\fR
Suppress auxiliary information
.IP
This program permits multiple edges and loops
