.TH SHOWG "1" "May 2009" "nauty 2.4" "User Commands"
.SH NAME
showg \- Write graphs in human\-readable format.
.SH SYNOPSIS
.B showg
[\fI\-p#:#l#o#Ftq\fR] [\fI\-a|\-A|\-c|\-d|\-e\fR] [\fIinfile \fR[\fIoutfile\fR]]
.SH DESCRIPTION
.IP
Write graphs in human\-readable format.
.IP
infile is the input file in graph6 or sparse6 format
outfile is the output file
Defaults are standard input and standard output.
.HP
\fB\-p\fR#, \fB\-p\fR#:#, \fB\-p\fR#\-# : only display one graph or a sequence of
.TP
graphs.
The first graph is number 1.  A second number
.IP
which is empty or zero means infinity.
.TP
\fB\-a\fR
: write the adjacency matrix
.TP
\fB\-A\fR
: same as \fB\-a\fR with a space between entries
.TP
\fB\-d\fR
: write output to satisfy dreadnaut
.TP
\fB\-c\fR
: write compact dreadnaut form with minimal line\-breaks
.TP
\fB\-e\fR
: write a list of edges, preceded by the order and the
.IP
number of edges
.HP
\fB\-o\fR# : specify number of first vertex (default is 0)
.TP
\fB\-t\fR
: write upper triangle only (affects \fB\-a\fR, \fB\-A\fR, \fB\-d\fR and default)
.TP
\fB\-F\fR
: write a form\-feed after each graph except the last
.HP
\fB\-l\fR# : specify screen width limit (default 78, 0 means no limit)
.IP
This is not currently implemented with \fB\-a\fR or \fB\-A\fR.
.TP
\fB\-q\fR
: suppress auxiliary output
.HP
\fB\-a\fR, \fB\-A\fR, \fB\-c\fR, \fB\-d\fR and \fB\-e\fR are incompatible.
